import { Inter } from "next/font/google";
import "./globals.css";
// import Providers from "./Provider/page";
// import ThemeSwitcher from "./ThemeProvider/page";
import ThemeProvider from './../components/theme-provider'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
    <body className={`${inter.className} `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
          {/* {children} */}

        {/* <Providers>
          <header className="py-6">
            <nav className="container flex items-center justify-center">
              <ThemeSwitcher />
            </nav>
          </header>
          {children}
        </Providers> */}
      </body>
    </html>
  );
}
